# Generated by Django 6.0.6 on 2026-07-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('jute_mon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=50, unique=True)),
                ('id_no', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('under_project', models.CharField(max_length=100)),
                ('c_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('d1_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('d2_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('e1_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('e2_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('smr_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
