# Generated by Django 6.0.6 on 2026-07-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuteRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('effect_date', models.DateField(default='2026-01-01', verbose_name='রেট কার্যকর হওয়ার তারিখ')),
                ('c_rate', models.FloatField(default=5800.0, verbose_name='C Rate')),
                ('d1_rate', models.FloatField(default=5650.0, verbose_name='D(I) Rate')),
                ('d2_rate', models.FloatField(default=5500.0, verbose_name='D(II) Rate')),
                ('e1_rate', models.FloatField(default=5300.0, verbose_name='E(I) Rate')),
                ('e2_rate', models.FloatField(default=5100.0, verbose_name='E(II) Rate')),
                ('smr_rate', models.FloatField(default=4925.0, verbose_name='SMR Rate')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effect_date'],
            },
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='total_mds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='date',
            field=models.DateField(),
        ),
    ]
