# Generated by Django 6.0.6 on 2026-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_juterate_gradeentry_total_mds_alter_gradeentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='juterate',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True, verbose_name='AI কনফিডেন্স স্কোর (%)'),
        ),
        migrations.AddField(
            model_name='juterate',
            name='predicted_next_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='AI আনুমানিক আগামী রেট'),
        ),
        migrations.AlterField(
            model_name='juterate',
            name='effect_date',
            field=models.DateField(default='2026-01-01', verbose_name='রেট কার্যকর হওয়ার তারিখ'),
        ),
    ]
