# Generated by Django 6.0.6 on 2026-07-22 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_juterate_ai_confidence_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billentry',
            name='center',
            field=models.CharField(blank=True, choices=[('center_1', 'সেন্টার ১'), ('center_2', 'সেন্টার ২'), ('center_3', 'সেন্টার ৩'), ('center_4', 'সেন্টার ৪'), ('center_5', 'সেন্টার ৫'), ('center_6', 'সেন্টার ৬'), ('center_7', 'সেন্টার ৭'), ('center_8', 'সেন্টার ৮'), ('center_9', 'সেন্টার ৯'), ('center_10', 'সেন্টার ১০')], max_length=50, null=True, verbose_name='সেন্টার'),
        ),
        migrations.AddField(
            model_name='billentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='অপারেটর'),
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='center',
            field=models.CharField(blank=True, choices=[('center_1', 'সেন্টার ১'), ('center_2', 'সেন্টার ২'), ('center_3', 'সেন্টার ৩'), ('center_4', 'সেন্টার ৪'), ('center_5', 'সেন্টার ৫'), ('center_6', 'সেন্টার ৬'), ('center_7', 'সেন্টার ৭'), ('center_8', 'সেন্টার ৮'), ('center_9', 'সেন্টার ৯'), ('center_10', 'সেন্টার ১০')], max_length=50, null=True, verbose_name='সেন্টার'),
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='অপারেটর'),
        ),
        migrations.AddField(
            model_name='juterate',
            name='center',
            field=models.CharField(blank=True, choices=[('center_1', 'সেন্টার ১'), ('center_2', 'সেন্টার ২'), ('center_3', 'সেন্টার ৩'), ('center_4', 'সেন্টার ৪'), ('center_5', 'সেন্টার ৫'), ('center_6', 'সেন্টার ৬'), ('center_7', 'সেন্টার ৭'), ('center_8', 'সেন্টার ৮'), ('center_9', 'সেন্টার ৯'), ('center_10', 'সেন্টার ১০')], max_length=50, null=True, verbose_name='সেন্টার'),
        ),
        migrations.AddField(
            model_name='juterate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='অপারেটর'),
        ),
    ]
