# Generated by Django 6.0.6 on 2026-07-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_billentry_center_billentry_user_gradeentry_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeentry',
            name='lot_no',
            field=models.CharField(max_length=50),
        ),
    ]
