# Generated by Django 6.0.7 on 2026-08-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_gradeentry_lot_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeentry',
            name='total_mds',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
