# Generated by Django 6.0.7 on 2026-08-08 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_gradeentry_total_mds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billentry',
            name='center',
            field=models.CharField(blank=True, choices=[('center_1', 'সেন্টার ১'), ('center_2', 'সেন্টার ২'), ('center_3', 'সেন্টার ৩'), ('center_4', 'সেন্টার ৪'), ('center_5', 'সেন্টার ৫'), ('center_6', 'সেন্টার ৬'), ('center_7', 'সেন্টার ৭'), ('center_8', 'সেন্টার ৮'), ('center_9', 'সেন্টার ৯'), ('center_10', 'সেন্টার ১০')], max_length=50, null=True, verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='billentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='center',
            field=models.CharField(blank=True, choices=[('center_1', 'সেন্টার ১'), ('center_2', 'সেন্টার ২'), ('center_3', 'সেন্টার ৩'), ('center_4', 'সেন্টার ৪'), ('center_5', 'সেন্টার ৫'), ('center_6', 'সেন্টার ৬'), ('center_7', 'সেন্টার ৭'), ('center_8', 'সেন্টার ৮'), ('center_9', 'সেন্টার ৯'), ('center_10', 'সেন্টার ১০')], max_length=50, null=True, verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='juterate',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True, verbose_name='AI Score %'),
        ),
        migrations.AlterField(
            model_name='juterate',
            name='center',
            field=models.CharField(blank=True, choices=[('center_1', 'সেন্টার ১'), ('center_2', 'সেন্টার ২'), ('center_3', 'সেন্টার ৩'), ('center_4', 'সেন্টার ৪'), ('center_5', 'সেন্টার ৫'), ('center_6', 'সেন্টার ৬'), ('center_7', 'সেন্টার ৭'), ('center_8', 'সেন্টার ৮'), ('center_9', 'সেন্টার ৯'), ('center_10', 'সেন্টার ১০')], max_length=50, null=True, verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='juterate',
            name='effect_date',
            field=models.DateField(default='2026-01-01', verbose_name='R.Eff.Date'),
        ),
        migrations.AlterField(
            model_name='juterate',
            name='predicted_next_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Prediction Rate'),
        ),
        migrations.AlterField(
            model_name='juterate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
    ]
