# Generated by Django 6.0.7 on 2026-08-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_alter_billentry_center_alter_billentry_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
